

name: "Setup Rust"
description: "Setup Rust"
runs:
  using: "composite"
  steps:
      - name: Set up cargo cache
        uses: actions/cache@v3
        continue-on-error: true
        with:
          path: ${{ env.CARGO_CACHE_PATH }}
          key: cargo-${{ runner.os }}-cargo-build-${{ hashFiles('**/Cargo.lock') }}

      - name: Get Rustc version
        run: |
          source scripts/ci/rust-version.sh
          echo "PLUGIN_RUST_VERSION=$rust_stable" >> $GITHUB_ENV
        shell: bash

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ env.PLUGIN_RUST_VERSION }}
          override: true
          profile: minimal