name: "Setup Rust"
description: "Setup Rust"
runs:
  using: "composite"
  steps:
      - name: Set up cargo cache
        uses: actions/cache@v3
        continue-on-error: true
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/            
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-

      - name: Get Rustc version
        run: |
          source scripts/ci/rust-version.sh
          echo "PLUGIN_RUST_VERSION=$rust_stable" >> $GITHUB_ENV
        shell: bash

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ env.PLUGIN_RUST_VERSION }}
          override: true
          profile: minimal
          components: rustfmt

      # - uses: Swatinem/rust-cache@v2
      #   with:
      #     cache-on-failure: true
      #     shared-key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
