name: Bump version and build

on:
  workflow_dispatch:

env:
  RUSTUP_HOME: ${{ github.workspace }}/rustup
  CARGO_HOME: ${{ github.workspace }}/cargo

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal

    - name: Install cargo-edit
      run: cargo install cargo-edit

    - name: Install jq
      run: |
        if ! command -v jq &> /dev/null
        then
          sudo apt-get update
          sudo apt-get install jq -y
        fi

    - name: Update version and build
      run: |
        ./bump_version.sh --bump minor --dry-run
        ./bump_version.sh --bump minor
