name: Release

on:
  push:
    tags:
      - "v*"
  pull_request:
    paths:
      - ".github/workflows/release.yml"

env:
  CARGO_TERM_COLOR: always

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          profile: minimal
          components: rustfmt

      - name: Check Solana version
        run: |
          echo "CI_TAG=${GITHUB_REF#refs/*/}" >> "$GITHUB_ENV"
          echo "CI_OS_NAME=linux" >> "$GITHUB_ENV"
          SOLANA_VERSION="$(./scripts/ci/solana-version.sh)"
          SOLANA_VERSION="v${SOLANA_VERSION#=}"
          echo "SOLANA_VERSION=$SOLANA_VERSION" >> "$GITHUB_ENV"

      - name: Grant permissions to create-tarball.sh
        run: chmod +x ./scripts/ci/create-tarball.sh

      - name: Grant permissions to build-all.sh
        run: chmod +x ./scripts/build-all.sh

      - name: Build release tarball
        run: ./scripts/ci/create-tarball.sh

      - name: Release
        uses: softprops/action-gh-release@v1
        run:
          echo "RUST_STABLE=$(rustc -V)" | tee -a $GITHUB_ENV
        if: startsWith(github.ref, 'refs/tags/')
        with:
          body: |
            clockwork-geyser-plugin ${{ env.CI_TAG }}
            solana ${{ env.SOLANA_VERSION }}
            rust ${{ env.RUST_STABLE }}
          files: |
            clockwork-geyser-plugin-release-*

      - name: Install cargo-publish-workspace-v2
        uses: baptiste0928/cargo-install@v2
        with:
          crate: cargo-publish-workspace-v2

      - name: Publish to crates.io
        run: cargo publish-workspace --crate-prefix mat-clockwork
